Vagrant::Config.run do |config|
  config.vm.forward_port(80,8888)
  config.vm.forward_port(22,3333)

  config.vm.box = "edev_squeeze"
  config.vm.box_url = "http://bonci.net/edev_squeeze.box"
  config.ssh.private_key_path = "./edev_root"
  config.ssh.username = "root"
  
  config.vm.share_folder("dropfiles","/dropfiles","./dropfiles")
  config.vm.customize ["modifyvm", :id, "--cpuexecutioncap", "50"]  
  
  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = "cookbooks"
    chef.roles_path = "roles"
    #chef.json = JSON.parse(File.read(File.dirname(__FILE__) + "/config/node.json"))
    chef.add_role("e2dev")
    chef.add_recipe("edev")
  end
end
