name: push-to-codecommit
on:
  push:
    branches: [ master ]
jobs:
  codecommit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: pushes to codecommit
        env:
          CODECOMMIT_SSH_KEY: ${{ secrets.CODECOMMIT_SSH_KEY }}
        shell: bash
        run: |
          mkdir ~/.ssh && cd ~/.ssh && echo "$CODECOMMIT_SSH_KEY" > id_rsa && chmod 600 id_rsa
          ssh-keyscan -H git-codecommit.us-west-2.amazonaws.com 2>/dev/null > known_hosts && chmod 600 known_hosts && cd -
          git remote add codecommit "ssh://APKATWVZOXOZ3G5UMC7H@git-codecommit.us-west-2.amazonaws.com/v1/repos/everything2"
          git push codecommit --mirror --force
